name: Deployment
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - '.github/**'
      - 'README.md'
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: publish
      run: dotnet publish EleccionesPeru2021/WebApp/WebApp.csproj --configuration Release   
    - name: .nojekyll
      run: touch /home/runner/work/eleccionesperu2021/eleccionesperu2021/EleccionesPeru2021/WebApp/bin/Release/net5.0/wwwroot/.nojekyll
    - uses: maxheld83/ghpages@master
      name: gh-pages publish
      env:
        BUILD_DIR: /home/runner/work/eleccionesperu2021/eleccionesperu2021/EleccionesPeru2021/WebApp/bin/Release/net5.0/publish/wwwroot
        GH_PAT: ${{ secrets.PUBLISH_TOKEN }}